### ISSUE TITLE
Download required input data files from ABS TableBuilder

### ISSUE THREAD

**Issue by wniroshan** [agentsoz/synthetic-population#1]
Below are the data sets to download. The codes in brackets refer to codes used by ABS.

- [x] 1. Distribution of persons based on age (AGE5P), sex (SEXP) and relationship status (RLHP) for each SA2 in Victoria
- [x] 2. Distribution of dwellings (households) based on number of persons (NPRD) in household and family household composition (HCFMD) for each SA2 in Victoria
- [x] 3. The distribution of households by NPRD and HCFMD at SA1 level grouped in corresponding SA2s
- [x] 4. ESRI shapefiles for all Victorian addresses, which will be used to assign geographical location of households
- [x] 5. ESRI shapefile for all SA2s in Australia, which will be used to extract Victorian SA2s
- [x] 6. ESRI shapefile for all SA1s in Australia, which will be used to extract Victorian SA1s

**Comment by wniroshan** [comment]
The location for vicmap address files: https://www.data.vic.gov.au/data/dataset/address-vicmap-address
The meta data on vicmap addresses http://services.land.vic.gov.au/catalogue/metadata?anzlicId=ANZVI0803003126&publicId=guest&extractionProviderId=1#tab2

**Comment by wniroshan** [comment]
The location for 2016 SA2 and SA1 shapefiles: http://www.abs.gov.au/AUSSTATS/abs@.nsf/DetailsPage/1270.0.55.001July%202016?OpenDocument

**Comment by wniroshan** [comment]
All the downloaded data are available in `data/melbourne/raw/`

**Comment by dhixsingh** [comment]
As of commit b65cea9a198eb4301301b7857d16df8f655c05df files are in [data/melbourne/raw](https://github.com/agentsoz/synthetic-population/tree/b65cea9a198eb4301301b7857d16df8f655c05df/data/melbourne/raw). Noting this here in case we change the directory structure again down the track.
