### ISSUE TITLE
Double-check why West Melbourne has no population in the Persons/HH files.

### ISSUE THREAD

**Issue by dhixsingh** [agentsoz/synthetic-population#12]
See `synthetic-population/data/melbourne/raw/Persons_2016_Greater_Melbourne_SA2.zip`

**Comment by wniroshan** [comment]
West Melbourne is an industrial SA2 covers the area between North Melbourne train station and  Maribymong River. So the data are correct.
http://www.censusdata.abs.gov.au/census_services/getproduct/census/2016/quickstat/206041127
