### ISSUE TITLE
Setup JUnit testing for java code

### ISSUE THREAD

**Issue by dhixsingh** [agentsoz/synthetic-population#19]
For instance, create unit tests for `src/main/java/bnw/abm/intg/synthesis/ExtrasHandler.java`.

For system level testing, see something like [MainMaldon600Test](https://github.com/agentsoz/bdi-abm-integration/blob/8ee3d73975f68fae2833ff01ec8c64e01b93a06f/examples/bushfire/src/test/java/io/github/agentsoz/ees/MainMaldon600Test.java). Unit test example is [BeliefSetTest](https://github.com/agentsoz/jill/blob/dev/jill/src/test/java/io/github/agentsoz/jill/core/beliefbase/BeliefSetTest.java). Randoop auto-generated test script is [here](https://github.com/agentsoz/jill/tree/dev/qa/randoop) and example output in [BeliefBaseExceptionRegressionTest0](https://github.com/agentsoz/jill/blob/dev/jill/src/test/java/io/github/agentsoz/jill/core/beliefbase/BeliefBaseExceptionRegressionTest0.java).

**Comment by wniroshan** [comment]
Junit set up complete in commit 04b394b

**Comment by dhixsingh** [comment]
Ensure that we have tests for #15 and #20.

**Comment by wniroshan** [comment]
Tests for #15 and #20 are included in ab1348b. Regression tests in 05e164a
