### ISSUE TITLE
Update the program to assign households to addresses in whole Greater Melbourne area

### ISSUE THREAD

**Issue by wniroshan** [agentsoz/synthetic-population#22]
At the moment the program locates the SA1 that each address belongs to with in Darebin North, Darebin South and Banyule SA3s. This needs to be extended to run for whole Greater Melbourne.

**Comment by dhixsingh** [comment]
Potentially we now want to do this at mesh block level which will be a simpler algorithm for finding the SA1 id for a given address. Currently we do this by searching if the `x,y` of a street adress falls within a SA1 which is a costly computation.

The new process would be to:
1. For a given street address in `data/melbourne/raw/SDM465215.zip`, get its associated `MESH_BLOCK` (mesh block id).
1. Use the above mesh block id to look up the SA1 for that mesh block, from `data/melbourne/raw/1270055001_mb_2016_vic_shape.zip`.
1. In some cases, the `MESH_BLOCK` id might not match (names might have changed), in which case we will have to revert to the current method.
