### ISSUE TITLE
Document different accuracy levels of household and person characteristics

### ISSUE THREAD

**Issue by wniroshan** [agentsoz/synthetic-population#6]
Documenting:
- [x] Describe which characteristics are maintained accurately (as per input distributions) when the household structures are formed.
- [x] Describe how new characteristics can be introduced to the population and what level of accuracy can be expected in the final population.
- [x] Describe the accuracy of the constructed population at SA1 level.

**Comment by dhixsingh** [comment]
This can be sections in the readme file (see #11).

**Comment by wniroshan** [comment]
Updated in 5220559
